from .factory_create_view import factory_create
from .factory_update_view import factory_update
from .get_factories_view import get_factories
from .get_machines_view import get_machines
from .get_user_factories_view import get_user_factories
from .get_user_view import get_users
from .home_view import home
from .is_user_admin_view import is_user_admin
from .login_required_decorator import login_required
from .login_view import login
from .logout_view import logout_view
from .machine_create_view import machine_create
from .machine_update_view import machine_update
from .update_user_view import update_user
from .user_register_view import user_register